new TypeIt("#myElement")
  .type("Hello. My name is")
    .pause(1000)
    .break()
    .type("NENYE DIEI")
    .break()
    .pause(1000)
    .type("I am a full stack web developer")
    .pause(2000)
    .delete(24)
    .type("Front End Developer")
    .pause(2000)
    .delete(21)
    .type("obsessed with writing code")
    .pause(2000)
    .delete(31)
    .pause(1000)
    .type("I am a Full Stack Developer")
  .go();